apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application
  labels:
    app: test-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-application
  template:
    metadata:
      labels:
        app: test-application
    spec:
      containers:
        - name: test-application
          image: divya2228/test-application:v1.0
          ports:
            - containerPort: 8080
