apiVersion: v1
kind: Service
metadata:
  name: test-application-service
spec:
  type: LoadBalancer
  selector:
    app: test-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
